apiVersion: v1
kind: Namespace
metadata:
  name: frigate
  labels:
    name: frigate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        env:
        - name: FRIGATE_RTSP_USER
          value: 'vmware'
        - name: FRIGATE_RTSP_PASSWORD
          value: 'VMware1!'
        securityContext:
          privileged: true
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: frigate-pv-data
            mountPath: '/config'
      volumes:
      - name: frigate-pv-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-nodeport
  namespace: frigate
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: frigate
